# Generated by Django 3.0 on 2023-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0005_auto_20230903_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
