# Generated by Django 3.0 on 2023-09-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0006_confirmed_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event_description',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
