# Generated by Django 3.0 on 2023-09-06 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0008_add_orphan_addoptentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oname', models.CharField(max_length=100)),
                ('chairman', models.CharField(max_length=100)),
                ('Olocation', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=100)),
                ('Land_line', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('established_date', models.DateField()),
                ('Msc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
