# Generated by Django 3.0 on 2023-09-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0009_orphanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_orphan',
            name='mother_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
