# Generated by Django 3.0 on 2023-09-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0010_auto_20230906_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_orphan',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='add_orphan',
            name='mother_name',
        ),
    ]
