# Generated by Django 3.0 on 2023-09-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0011_auto_20230906_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_orphan',
            name='father_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='add_orphan',
            name='mother_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
