# Generated by Django 3.0 on 2023-09-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0012_auto_20230906_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_orphan',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
