# Generated by Django 3.0 on 2023-09-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0013_add_orphan_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_medicalcertificate',
            new_name='is_addoptent',
        ),
        migrations.AlterField(
            model_name='add_orphan',
            name='age',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
