# Generated by Django 3.0 on 2023-09-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0014_auto_20230907_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptentlogin',
            old_name='gender',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='adoptentlogin',
            old_name='address',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='adoptentlogin',
            old_name='name',
            new_name='have_child',
        ),
        migrations.RemoveField(
            model_name='adoptentlogin',
            name='mobile',
        ),
        migrations.AddField(
            model_name='adoptentlogin',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='adoptentlogin',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
