# Generated by Django 3.0 on 2023-09-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0015_auto_20230907_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptentlogin',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
