# Generated by Django 3.0 on 2023-09-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0016_adoptentlogin_medical_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptentlogin',
            name='occupation',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
