# Generated by Django 3.0 on 2023-09-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0017_adoptentlogin_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptentlogin',
            name='monthly_income',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
