# Generated by Django 3.0 on 2023-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0019_add_orphan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_orphan',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='image/'),
        ),
    ]
