# Generated by Django 3.0 on 2023-09-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0020_auto_20230908_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_orphan',
            name='image',
        ),
    ]
