# Generated by Django 3.0 on 2023-09-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0021_remove_add_orphan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_orphan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orphan_images/'),
        ),
    ]
