# Generated by Django 3.0 on 2023-09-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0022_add_orphan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_orphan',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='orphan_images/'),
        ),
    ]
