# Generated by Django 3.0 on 2023-09-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0023_auto_20230909_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_orphan',
            name='image',
        ),
    ]
