# Generated by Django 3.0 on 2023-09-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrphanageApp', '0024_remove_add_orphan_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptentlogin',
            old_name='aadhar_number',
            new_name='aadhaar_number',
        ),
        migrations.RenameField(
            model_name='confirmed_events',
            old_name='aadhar',
            new_name='aadhaar',
        ),
        migrations.RenameField(
            model_name='eventbooking',
            old_name='aadhar',
            new_name='aadhaar',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='aadhar',
            new_name='aadhaar',
        ),
    ]
